name: check-bump-version

on:
  pull_request:
    paths:
      - 'package.json'
      - 'src/**/*.ts'
    branches: [main]

concurrency:
  group: check-bump-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check-bump-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: avides/actions-project-version-check@v1.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: package.json

  auto-bump-version:
    runs-on: ubuntu-latest
    needs:
      - check-bump-version
    if: ${{ always() && contains(needs.check-bump-version.result, 'failure') }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Bump version
        run: yarn version --patch --no-git-tag-version

      - uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: bump version'
          default_author: github_actions
